# Generated by Django 6.0.6 on 2026-06-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('nazione', models.CharField(max_length=100)),
                ('dataNascita', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('dataMorte', models.DateField(blank=True, null=True)),
                ('pathImmagine', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('superficie', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('annoAcquisto', models.IntegerField()),
                ('annoRealizzazione', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('pathImmagine', models.CharField(blank=True, max_length=255, null=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museo.autore')),
                ('espostaInSala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museo.sala')),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='temaSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museo.tema'),
        ),
    ]
